title: Vue on Django
description: >- # this means to ignore newlines until "baseurl:"
  A Choose-Your-Own-Adventure of topics and articles surrounding Vue,
  Django, and how they get along together.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.vue-on-django.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: paytastic
github_username:  rpalo

collections:
  tutorials:
    output: true
    permalink: pretty

source: src
timezone: America/Los_Angeles
port: 4545

# Build settings
markdown: kramdown
profile: true
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
